-- Generated by nwg-displays on 2026-06-27 at 15:30:05. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "DP-5",
    mode = "1920x1080@119.98",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-6",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1.0
})
