-- Generated by nwg-displays on 2026-06-27 at 15:30:05. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "1920x0",
    scale = 1.25
})

hl.monitor({
    output = "DP-3",
    mode = "1920x1080@165",
    position = "0x0",
    scale = 1.0
})

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1"
})


hl.workspace_rule({
    workspace = "2",
    monitor = "DP-3"
})
