-- Generated by nwg-displays on 2026-06-27 at 15:32:06. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-5",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-6",
    default = true
})
