general {
    col.active_border = rgba(938f9977)
    col.inactive_border = rgba(48454e55)
}

misc {
    background_color = rgba(141318FF)
}

windowrule = border_color rgba(cdbdffAA) rgba(cdbdff77), match:pin 1
