source = /home/hayden/.config/hypr/hyprlock/colors.conf

# BACKGROUND
background {
    path = ~/Pictures/Wallpapers/active_wallpaper
    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}
# POWER OFF
label {
    monitor =
    text = 
    color = $text_color
    font_size = 28
    font_family = JetBrainsMono Nerd Font Propo
    position = -60, -350
    halign = center
    valign = center
    onclick = systemctl poweroff
}

# REBOOT
label {
    monitor =
    text = 
    color = $text_color
    font_size = 28
    font_family = JetBrainsMono Nerd Font Propo
    position = 0, -350
    halign = center
    valign = center
    onclick = systemctl reboot
}

# SUSPEND
label {
    monitor =
    text = 󰤄
    color = $text_color
    font_size = 28
    font_family = JetBrainsMono Nerd Font Propo
    position = 60, -350
    halign = center
    valign = center
    onclick = systemctl suspend
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    border_color = $entry_border_color
    inner_color = $entry_border_color
    font_color = $text_color
    fade_on_empty = false
    rounding = 18
    check_color = $text_color
    fail_color = rgba(ff5555ff)
    placeholder_text = Input Password or Scan Fingerprint...
    fade_on_empty = false
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
    font_family = SF Pro
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = $text_color
  font_size = 22
  font_family = SF Mono
  position = 0, 300
  halign = center
  valign = center
}

# TIME
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%-I:%M")"
  color = $foreground
  font_size = 95
  font_family = SF Pro, Extrablack
  position = 0, 200
  halign = center
  valign = center
}


