exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
submap = global # This is required for catchall to work

source=env.conf
source=execs.conf
source=general.conf
source=rules.conf
source=colors.conf
source=keybinds.conf

