cursor            #ffb0ca
cursor_text_color #191114

foreground            #efdfe2
background            #191114

selection_foreground  #efdfe2
selection_background  #6f334a

url_color             #ffd9e3

#: black 000000 767676
color0  #261d20
color8  #3c3235

#: red cc0403 f2201f
color1  #ffb4ab
color9  #93000a

#: green 19cb00 23fd00
color2  #f0bc95
color10 #623f21

#: yellow cecb00 fffd00
color3  #e2bdc7
color11 #5a3f48

#: blue 0d73cc 1a8fff
color4  #ffb0ca
color12 #6f334a

#: magenta cb1ed1 fd28ff
color5  #e2bdc7
color13 #ffd9e3

#: cyan 0dcdcd 14ffff
color6  #f0bc95
color14 #ffdcc3

#: white dddddd ffffff
color7  #d5c2c6
color15 #efdfe2

mark1_foreground #ffd9e3
mark1_background #6f334a

mark2_foreground #ffd9e3
mark2_background #5a3f48

mark3_foreground #ffdcc3
mark3_background #623f21

active_tab_foreground #541d34
active_tab_background #ffb0ca

inactive_tab_foreground #d5c2c6
inactive_tab_background #261d20

active_border_color #ffb0ca
inactive_border_color #31282a

# bell_border_color #ff5a00
