cursor            #e2b7f4
cursor_text_color #161217

foreground            #e9e0e7
background            #161217

selection_foreground  #e9e0e7
selection_background  #5b396c

url_color             #f6d9ff

#: black 000000 767676
color0  #221e24
color8  #383339

#: red cc0403 f2201f
color1  #ffb4ab
color9  #93000a

#: green 19cb00 23fd00
color2  #f5b7b6
color10 #663b3b

#: yellow cecb00 fffd00
color3  #d4c0d8
color11 #504255

#: blue 0d73cc 1a8fff
color4  #e2b7f4
color12 #5b396c

#: magenta cb1ed1 fd28ff
color5  #d4c0d8
color13 #f0dcf4

#: cyan 0dcdcd 14ffff
color6  #f5b7b6
color14 #ffdad9

#: white dddddd ffffff
color7  #cec3ce
color15 #e9e0e7

mark1_foreground #f6d9ff
mark1_background #5b396c

mark2_foreground #f0dcf4
mark2_background #504255

mark3_foreground #ffdad9
mark3_background #663b3b

active_tab_foreground #432254
active_tab_background #e2b7f4

inactive_tab_foreground #cec3ce
inactive_tab_background #221e24

active_border_color #e2b7f4
inactive_border_color #2d282e

# bell_border_color #ff5a00
