cursor            #dfc56d
cursor_text_color #16130b

foreground            #e9e2d4
background            #16130b

selection_foreground  #e9e2d4
selection_background  #564500

url_color             #fde186

#: black 000000 767676
color0  #221f17
color8  #38342b

#: red cc0403 f2201f
color1  #ffb4ab
color9  #93000a

#: green 19cb00 23fd00
color2  #abd0b0
color10 #2e4e36

#: yellow cecb00 fffd00
color3  #d3c6a1
color11 #4f462a

#: blue 0d73cc 1a8fff
color4  #dfc56d
color12 #564500

#: magenta cb1ed1 fd28ff
color5  #d3c6a1
color13 #f0e2bb

#: cyan 0dcdcd 14ffff
color6  #abd0b0
color14 #c7eccb

#: white dddddd ffffff
color7  #cec6b4
color15 #e9e2d4

mark1_foreground #fde186
mark1_background #564500

mark2_foreground #f0e2bb
mark2_background #4f462a

mark3_foreground #c7eccb
mark3_background #2e4e36

active_tab_foreground #3b2f00
active_tab_background #dfc56d

inactive_tab_foreground #cec6b4
inactive_tab_background #221f17

active_border_color #dfc56d
inactive_border_color #2d2a21

# bell_border_color #ff5a00
